In [1]:
import os
from google.colab import drive

drive.mount('/content/drive')
path = "/content/drive/My Drive/Datamining/TextMining/Dataset/"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
import pandas as pd
import random
import csv

In [3]:
!cp "drive/My Drive/Colab Notebooks/TP Text Mining/functions.py" .
import functions as f
import importlib
importlib.reload(f)
f.v()

2020-05-24 14:13

In [5]:
df = f.loadDatasets(path)
df

                date  ... language_proba
0         2019-05-10  ...       0.000000
1         2019-05-10  ...       0.000000
2         2019-05-10  ...       0.980272
3         2019-05-10  ...       0.449887
4         2019-05-10  ...       0.685419
...              ...  ...            ...
11867881  2019-11-23  ...       0.939878
11867882  2019-11-23  ...       0.457228
11867883  2019-11-23  ...       0.884063
11867884  2019-11-23  ...       0.925460
11867885  2019-11-23  ...       0.950643

[11867886 rows x 4 columns]

In [6]:
df['month'] = df.date.apply(lambda date: f.getMonth(date))
df

                date  ... month
0         2019-05-10  ...     5
1         2019-05-10  ...     5
2         2019-05-10  ...     5
3         2019-05-10  ...     5
4         2019-05-10  ...     5
...              ...  ...   ...
11867881  2019-11-23  ...    11
11867882  2019-11-23  ...    11
11867883  2019-11-23  ...    11
11867884  2019-11-23  ...    11
11867885  2019-11-23  ...    11

[11867886 rows x 5 columns]

In [7]:
df.month.unique()

array([ 5,  6,  7,  8,  9, 10, 11])

In [8]:
df_countByMonth = df.groupby('month').size().reset_index(name = 'count')
df_countByMonth

   month    count
0      5  1468826
1      6  2197501
2      7  2199150
3      8  1699913
4      9  1667442
5     10  1552121
6     11  1082933

In [9]:
df_countByText = df.groupby('text').size().reset_index(name = 'count')
df_countByText

                                                       text  count
0                                                                3
1          $BTC $6243.00 and pumping!!!  #cryptocurrency...      1
2                                     $BTC BOOM!!! 7360.00       1
3          $LINK may go up  BINANCE  TRADINGVIEW: http:/...      1
4          BUY BTC@$7144.9 51.98% (+0.03) (LONG TERM)  B...      1
...                                                     ...    ...
10226027  🪂 Cryptoknowmics #Airdrop 💲 Claim up to ~US$25...      1
10226028  🪂 Freelanex Airdrop 💲 Value ≅ US$29.40 ≒ 7350 ...      1
10226029  🪂 Sologenic Airdrop 💲 Value ≅ US$10 ≒ 40 SOLO ...      1
10226030  🪂 XERA Airdrop 💲 Value ≅ US$15 ≒ 30 XERA + ⏩ R...      1
10226031                                                🪐🪐🪐      1

[10226032 rows x 2 columns]

In [10]:
df_countByText.sort_values(by = ['count'], ascending = False, inplace = True)
df_countByText

                                                       text  count
6812954                                 La ‘revolución’ del  89162
9137093   You ought to Take your time to check this! The...  65245
8469546   This team offers conditions at a first-class l...  60263
7921635   Shut up and take my money! How dare you say th...  54250
5343001   Crypto is my job and I take lots of time to in...  53132
...                                                     ...    ...
3443184   @skxtefn @skiezfn @CowboyFN_ Can you sent me B...      1
3443185   @sky @DACCblockchain spend 1k $btc and it is c...      1
3443186   @sky13372 "With children, happy to school" in ...      1
3443187   @sky20116018 Claim 10$ Free BTC Bonus Here: ht...      1
10226031                                                🪐🪐🪐      1

[10226032 rows x 2 columns]

In [11]:
df_countByText['count'].unique()

array([89162, 65245, 60263, 54250, 53132, 51101, 46553, 45565, 45137,
       39660, 30002, 26218,  7345,  5525,  5114,  4930,  4929,  4565,
        4559,  4435,  4043,  3723,  3053,  2998,  2951,  2902,  2897,
        2863,  2742,  2598,  2380,  2287,  2285,  2234,  2191,  2134,
        2093,  1891,  1798,  1764,  1669,  1646,  1595,  1528,  1485,
        1394,  1244,  1183,  1182,  1140,  1092,  1054,  1040,  1033,
        1027,  1020,  1008,   970,   965,   928,   904,   896,   883,
         882,   847,   839,   831,   807,   802,   797,   783,   770,
         765,   751,   733,   728,   718,   690,   679,   673,   664,
         648,   646,   643,   639,   626,   622,   617,   612,   610,
         602,   598,   591,   585,   582,   571,   569,   549,   547,
         545,   536,   534,   531,   507,   488,   485,   484,   482,
         480,   478,   476,   472,   468,   467,   459,   456,   439,
         438,   430,   429,   428,   427,   426,   413,   409,   408,
         402,   399,   394,   389,   386,   385,   384,   383,   381,
         380,   379,   377,   376,   375,   374,   373,   371,   370,
         369,   368,   367,   366,   365,   364,   363,   362,   361,
         360,   359,   358,   357,   356,   351,   349,   348,   347,
         345,   343,   341,   340,   335,   334,   332,   331,   329,
         328,   327,   324,   323,   322,   320,   319,   318,   317,
         316,   315,   314,   313,   312,   311,   310,   308,   307,
         306,   304,   300,   299,   298,   297,   296,   295,   294,
         292,   290,   288,   286,   285,   284,   283,   282,   281,
         280,   279,   278,   277,   276,   275,   274,   273,   272,
         271,   270,   269,   268,   267,   266,   265,   264,   263,
         262,   261,   260,   259,   257,   256,   255,   254,   253,
         252,   251,   250,   249,   247,   246,   245,   244,   243,
         242,   241,   240,   238,   237,   235,   233,   232,   231,
         230,   229,   228,   227,   226,   225,   224,   223,   222,
         220,   219,   218,   216,   215,   214,   213,   212,   211,
         210,   209,   208,   206,   205,   204,   203,   202,   201,
         200,   199,   198,   197,   196,   195,   194,   193,   192,
         191,   190,   189,   188,   187,   186,   185,   184,   183,
         182,   181,   180,   179,   178,   177,   176,   175,   174,
         173,   172,   171,   170,   169,   168,   167,   166,   165,
         164,   163,   162,   161,   160,   159,   158,   157,   156,
         155,   154,   153,   152,   151,   150,   149,   148,   147,
         146,   145,   144,   143,   142,   141,   140,   139,   138,
         137,   136,   135,   134,   133,   132,   131,   130,   129,
         128,   127,   126,   125,   124,   123,   122,   121,   120,
         119,   118,   117,   116,   115,   114,   113,   112,   111,
         110,   109,   108,   107,   106,   105,   104,   103,   102,
         101,   100,    99,    98,    97,    96,    95,    94,    93,
          92,    91,    90,    89,    88,    87,    86,    85,    84,
          83,    82,    81,    80,    79,    78,    77,    76,    75,
          74,    73,    72,    71,    70,    69,    68,    67,    66,
          65,    64,    63,    62,    61,    60,    59,    58,    57,
          56,    55,    54,    53,    52,    51,    50,    49,    48,
          47,    46,    45,    44,    43,    42,    41,    40,    39,
          38,    37,    36,    35,    34,    33,    32,    31,    30,
          29,    28,    27,    26,    25,    24,    23,    22,    21,
          20,    19,    18,    17,    16,    15,    14,    13,    12,
          11,    10,     9,     8,     7,     6,     5,     4,     3,
           2,     1])

In [12]:
df_countByText = df_countByText[df_countByText['count'] > 1]
df_countByText

                                                      text  count
6812954                                La ‘revolución’ del  89162
9137093  You ought to Take your time to check this! The...  65245
8469546  This team offers conditions at a first-class l...  60263
7921635  Shut up and take my money! How dare you say th...  54250
5343001  Crypto is my job and I take lots of time to in...  53132
...                                                    ...    ...
101466   #BTC First time in history, we have seen bitco...      2
6380186  I invite you to the contest "Giveaway | Earn $...      2
7585039  Price movements under $10K have only been a di...      2
1488386  94k Bitcoin (1B USD) transferred from unknown ...      2
6380436                                   I joined airdrop      2

[185403 rows x 2 columns]

In [0]:
df_countByText.to_csv(path + 'repetidos.csv', index = False, escapechar='\\', quotechar='"', encoding = "utf-8",
                quoting=csv.QUOTE_NONNUMERIC)

In [14]:
df_countByText["is_spam"] = df_countByText['count'] >= 2
df_countByText

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

                                                      text  count  is_spam
6812954                                La ‘revolución’ del  89162     True
9137093  You ought to Take your time to check this! The...  65245     True
8469546  This team offers conditions at a first-class l...  60263     True
7921635  Shut up and take my money! How dare you say th...  54250     True
5343001  Crypto is my job and I take lots of time to in...  53132     True
...                                                    ...    ...      ...
101466   #BTC First time in history, we have seen bitco...      2     True
6380186  I invite you to the contest "Giveaway | Earn $...      2     True
7585039  Price movements under $10K have only been a di...      2     True
1488386  94k Bitcoin (1B USD) transferred from unknown ...      2     True
6380436                                   I joined airdrop      2     True

[185403 rows x 3 columns]

In [15]:
df = f.addIsSpamColumnBasedOnTextRepeatedness(df)
df

                date  ... is_spam
0         2019-05-10  ...    True
1         2019-05-14  ...    True
2         2019-10-24  ...    True
3         2019-10-24  ...    True
4         2019-10-25  ...    True
...              ...  ...     ...
11867881  2019-11-23  ...   False
11867882  2019-11-23  ...   False
11867883  2019-11-23  ...   False
11867884  2019-11-23  ...   False
11867885  2019-11-23  ...   False

[11867886 rows x 6 columns]

In [16]:
# Mayo, Junio, Julio y Agosto para TRAIN
dfSample = f.getSampleWithNames(df[df['is_spam'] == False], [5, 6, 7, 8], 250)
dfSample.drop(['language', 'language_proba', 'is_spam'], axis = 1, inplace = True)
dfSample.sort_values(by = ['name', 'month'], inplace = True)
dfSample

           date  ...    name
3    2019-05-21  ...  Barbii
4    2019-05-22  ...  Barbii
12   2019-05-31  ...  Barbii
18   2019-05-29  ...  Barbii
26   2019-05-24  ...  Barbii
..          ...  ...     ...
972  2019-08-30  ...    Seba
980  2019-08-23  ...    Seba
985  2019-08-23  ...    Seba
988  2019-08-03  ...    Seba
997  2019-08-15  ...    Seba

[1000 rows x 4 columns]

In [17]:
dfSample_countByName = dfSample.groupby('name').size().reset_index(name = 'count')
dfSample_countByName

     name  count
0  Barbii    200
1    Juan    200
2   Mauro    200
3    Nico    200
4    Seba    200

In [0]:
dfSample.to_csv(path + 'sample_Train_May-Ago.csv', index = False, escapechar='\\', quotechar='"', encoding = "utf-8",
                quoting=csv.QUOTE_NONNUMERIC)

In [19]:
# Septiembre y Octubre para VALIDATION (nos queda Noviembre para TEST)
dfSample = f.getSampleWithNames(df[df['is_spam'] == False], [9, 10], 250)
dfSample.drop(['language', 'language_proba', 'is_spam'], axis = 1, inplace = True)
dfSample.sort_values(by = ['name', 'month'], inplace = True)
dfSample

           date  ...    name
2    2019-09-15  ...  Barbii
5    2019-09-19  ...  Barbii
8    2019-09-01  ...  Barbii
21   2019-09-23  ...  Barbii
29   2019-09-10  ...  Barbii
..          ...  ...     ...
479  2019-10-18  ...    Seba
481  2019-10-18  ...    Seba
485  2019-10-31  ...    Seba
491  2019-10-26  ...    Seba
497  2019-10-13  ...    Seba

[500 rows x 4 columns]

In [20]:
dfSample_countByName = dfSample.groupby('name').size().reset_index(name = 'count')
dfSample_countByName

     name  count
0  Barbii    100
1    Juan    100
2   Mauro    100
3    Nico    100
4    Seba    100

In [0]:
dfSample.to_csv(path + 'sample_Validation_Sep-Oct.csv', index = False, escapechar='\\', quotechar='"', encoding = "utf-8",
                quoting=csv.QUOTE_NONNUMERIC)